### ISSUE TITLE
Redesign Categories page to types

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#77]
- Redesign the page to match CSULB Waste Not website/brochure's color/layout  scheme/fonts
- Create a type list of: metal, plastic, glass, food, etc

**Comment by brysonsherman** [comment]
Pushed: Replaced "Categories" with "bins" and added "Types." Left "Category" type for items in database so other aspects in the project still pull the right items back, but added and Bin and a Type to all items. In order to do this I duplicated the category metadata and created 6 new "Type" metadata. Posting a new item will create new items with a bin and a type but not a category. 
Working on: updating the home page so that when a bin is clicked on it will pull back all of the items of that type. Then will move towards working on the edit item so admins may change types or bins in the future if that is needed

**Comment by violangreg** [comment]
10.29.18
- Added description
- Changed front-end list layout

Time: 1 hour and 30 minutes
