### ISSUE TITLE
Fix quiz bug

### ISSUE THREAD

**Issue by violangreg** [violangreg/CECS491A#90]
Choosing correct answer shows incorrect

**Comment by patrickly** [comment]
Fixed with this commit: https://github.com/WasteNotCSULB/WebApp/commit/3be5caff38440ecee3ca769c89225d33e37ec091

---
In the GET request for http://localhost:3030/api/itemsRandom, the bin's name is capitalized. So on the front-end, checking for "compost" will be futile. So we need to check for "Compost" with the capital C.
![Screen Shot 2018-10-23 at 1.26.36 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ae0ee69e323360011c5e9d6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236456f06b7191a379f1102d4f5c595ecc3c4a4356bcbbd671f3e57862804e0ebcd73b0e74903b40acec841cbb01ba748b1e87b7b5d844d2f42f67b6d5db1063474f4dcbed5727a19f41c95df24be24f53a3123362e7772431.png)
